# Generated by Django 5.1.1 on 2024-10-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargado_en', models.DateTimeField(auto_created=True)),
                ('alias', models.CharField(max_length=30)),
                ('nombre_completo', models.CharField(max_length=30)),
                ('aldea', models.CharField(max_length=30)),
                ('clan', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='personajes/')),
            ],
        ),
    ]
